
[general]
	retain_simplerpc_rpc_text = true
	toggle_mod = true
	retain_details = true
	show_details = true
	retain_time_elapsed = true
	retain_state = true
	select_details = 1
	retain_in_hycord = true
	show_image = true
	show_time_elapsed = true
	automatically_turn_off_mod_when_hycord_detected = false
	automatically_turn_off_mod_when_scc_detected = false
	retain_in_scc = true

[updater]
	show_update_notification = true

